#!/bin/bash

WM_PROJECT_DIR=/opt/openfoam5
source $WM_PROJECT_DIR/etc/bashrc
echo "version: " && foamVersion

cd ${0%/*} || exit 1    # Run from this directory
set -x

wclean libso

if [ -d Make/linux* ]; then
    rm -r Make/linux*
fi

#------------------------------------------------------------------------------
