#!/bin/bash

WM_PROJECT_DIR=/opt/openfoam5
source $WM_PROJECT_DIR/etc/bashrc
echo "version: " && foamVersion

cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

wmake $targetType

#------------------------------------------------------------------------------
# Extends the standard library for dynamic mesh refinement to allow combining
# multiple refinement conditions based on different fields.
#------------------------------------------------------------------------------
