#!/bin/bash

WM_PROJECT_DIR=/opt/openfoam6
source $WM_PROJECT_DIR/etc/bashrc
echo "version: " && foamVersion

cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake  $targetType dynamicMultiFieldRefineFvMesh
wmake  $targetType

#------------------------------------------------------------------------------
# Allows dynamic load balancing when working with dynamic meshes (not very
# stable yet...)
#
# A multi-field version has been merged, which extends the standard dynamic mesh
# refinement capabilities to allow combining multiple refinement conditions
# based on different fields.
#------------------------------------------------------------------------------
