#!/bin/bash

WM_PROJECT_DIR=/opt/openfoam6
source $WM_PROJECT_DIR/etc/bashrc
echo "version: " && foamVersion

cd ${0%/*} || exit 1    # Run from this directory

wclean dynamicMultiFieldRefineFvMesh
wclean

if [ -d dynamicMultiFieldRefineFvMesh/Make/linux* ]; then
    rm -r dynamicMultiFieldRefineFvMesh/Make/linux*
fi

if [ -d Make/linux* ]; then
    rm -r Make/linux*
fi

#------------------------------------------------------------------------------
